# Analýza dátových sád

## Dátová sada Prevádzky 

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

#### Načítame dátovú sadu prevádzok do pandas dataframe so správnym kódovaním a zobrazíme prvých 10 záznamov

In [4]:
df_facilities = pd.read_csv('Dataset/export-sluzby-2021-10.csv', encoding='cp1250', delimiter=';', header=0)
df_facilities.head(10)

ZdravotnickeZarizeniId  PCZ  PCDP                       NazevCely  \
0                  161440    0     3  Tormová Eleonóra MUDr., s.r.o.   
1                  161439    0     1         MDDr. Barbora Krybusová   
2                  161438    0     0           MUDr. Petra Havlíková   
3                  161437    0     0              Azzurro Neo s.r.o.   
4                  161436   24     0                  Renturi s.r.o.   
5                  161435    0     1     MUDr. Marian Sznapka s.r.o.   
6                  161434    0     0     MUDr. Marian Sznapka s.r.o.   
7                  161433    0     1                   JANA BLAŽKOVÁ   
8                  161432    0     0                Pavlína Peterová   
9                  161431    0     0                Bc. Zdeněk Novák   

   ZdravotnickeZarizeniKod  DruhZarizeniKod  \
0            3925595000003              320   
1            6890377000001              322   
2           11796120000000              324   
3            9983643000000              350   
4           28405757024000              320   
5           11748109000001              320   
6           11748109000000              320   
7           66130620000001              360   
8           11790644000000              359   
9            5786070000000              351   

                             DruhZarizeni DruhZarizeniSekundarni  \
0   Samost. ordinace všeob. prakt. lékaře                    NaN   
1    Samostatná ordinace PL - stomatologa                    NaN   
2  Samostatná ordinace lékaře specialisty                    NaN   
3                   Domácí zdravotní péče                    NaN   
4   Samost. ordinace všeob. prakt. lékaře                    NaN   
5   Samost. ordinace všeob. prakt. lékaře                    NaN   
6   Samost. ordinace všeob. prakt. lékaře                    NaN   
7     Samostatná stomatologická laboratoř                    NaN   
8     Samostatné zařízení nelékaře - jiné                    NaN   
9      Samostatné zařízení fyzioterapeuta                    NaN   

                     Obec      Psc  ... PscSidlo  ObecSidlo  \
0                 Olomouc  77900.0  ...  77900.0    Olomouc   
1                 Tovačov  75101.0  ...  75002.0     Přerov   
2               Mohelnice  78985.0  ...  78985.0  Mohelnice   
3                 Hranice  75301.0  ...  75301.0    Hranice   
4  Frenštát pod Radhoštěm  74401.0  ...  15000.0    Praha 5   
5                   Písek  73984.0  ...  73991.0  Jablunkov   
6               Jablunkov  73991.0  ...  73991.0  Jablunkov   
7                    Most  43401.0  ...  43401.0       Most   
8                   Děčín  40502.0  ...  40502.0      Děčín   
9                   Louny  44001.0  ...  44001.0      Louny   

          UliceSidlo CisloDomovniOrientacniSidlo  \
0         Fischerova                      723/24   
1         Kabelíkova                      2682/1   
2       nám. Svobody                      1022/2   
3           Radniční                          30   
4  náměstí 14. října                      1307/2   
5             Školní                         388   
6             Školní                         388   
7     Zdeňka Fibicha                     2825/47   
8           Teplická                     1850/60   
9          Fűgnerova                        1668   

                        OborPece  \
0  všeobecné praktické lékařství   
1                zubní lékařství   
2                    psychiatrie   
3               Všeobecná sestra   
4  všeobecné praktické lékařství   
5  všeobecné praktické lékařství   
6  všeobecné praktické lékařství   
7                  Zubní technik   
8           Dentální hygienistka   
9                  Fyzioterapeut   

                                           FormaPece DruhPece  \
0                                    ambulantní péče      NaN   
1                                    ambulantní péče      NaN   
2                                    ambulantní péče      NaN   
3  zdrav. péče posk

In [3]:
df_facilities.tail(10)

ZdravotnickeZarizeniId  PCZ  PCDP  \
61972                      97    0     0   
61973                      97    0     0   
61974                      97    0     0   
61975                      97    0     0   
61976                      97    0     0   
61977                      97    0     0   
61978                      97    0     0   
61979                      97    0     0   
61980                      97    0     0   
61981                      97    0     0   

                                         NazevCely  ZdravotnickeZarizeniKod  \
61972  Institut klinické a experimentální medicíny              23001000000   
61973  Institut klinické a experimentální medicíny              23001000000   
61974  Institut klinické a experimentální medicíny              23001000000   
61975  Institut klinické a experimentální medicíny              23001000000   
61976  Institut klinické a experimentální medicíny              23001000000   
61977  Institut klinické a experimentální medicíny              23001000000   
61978  Institut klinické a experimentální medicíny              23001000000   
61979  Institut klinické a experimentální medicíny              23001000000   
61980  Institut klinické a experimentální medicíny              23001000000   
61981  Institut klinické a experimentální medicíny              23001000000   

       DruhZarizeniKod DruhZarizeni DruhZarizeniSekundarni     Obec      Psc  \
61972              102    Nemocnice                    NaN  Praha 4  14000.0   
61973              102    Nemocnice                    NaN  Praha 4  14000.0   
61974              102    Nemocnice                    NaN  Praha 4  14000.0   
61975              102    Nemocnice                    NaN  Praha 4  14000.0   
61976              102    Nemocnice                    NaN  Praha 4  14000.0   
61977              102    Nemocnice                    NaN  Praha 4  14000.0   
61978              102    Nemocnice                    NaN  Praha 4  14000.0   
61979              102    Nemocnice                    NaN  Praha 4  14000.0   
61980              102    Nemocnice                    NaN  Praha 4  14000.0   
61981              102    Nemocnice                    NaN  Praha 4  14000.0   

       ... PscSidlo ObecSidlo UliceSidlo CisloDomovniOrientacniSidlo  \
61972  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61973  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61974  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61975  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61976  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61977  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61978  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61979  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61980  ...  14000.0   Praha 4   Vídeňská                      1958/9   
61981  ...  14000.0   Praha 4   Vídeňská                      1958/9   

                 OborPece                       FormaPece         DruhPece  \
61972  Klinický psycholog  akutní lůžková péče intenzivní              NaN   
61973  Klinický psycholog  akutní lůžková péče standardní              NaN   
61974  Klinický psycholog                 ambulantní péče              NaN   
61975    Klinický logoped                 ambulantní péče              NaN   
61976   gastroenterologie  akutní lůžková péče intenzivní              NaN   
61977   gastroenterologie  akutní lůžková péče standardní              NaN   
61978   gastroenterologie                 ambulantní péče              NaN   
61979   lékařská genetika                 ambulantní péče              NaN   
61980   klinická farmacie                             NaN  lékárenská péče   
61981  klinická onkologie                 ambulantní péče              NaN   

                                         OdbornyZastupce  \
61972  Marek Šetina, Mgr. Martina Šochmanová, Michal ...   

In [4]:
print("Počet riadkov (dátová sada prevádzok):", len(df_facilities.index))

Počet riadkov (dátová sada prevádzok): 61982


In [5]:
df_facilities.dtypes

ZdravotnickeZarizeniId           int64
PCZ                              int64
PCDP                             int64
NazevCely                       object
ZdravotnickeZarizeniKod          int64
DruhZarizeniKod                  int64
DruhZarizeni                    object
DruhZarizeniSekundarni          object
Obec                            object
Psc                            float64
Ulice                           object
CisloDomovniOrientacni          object
Kraj                            object
KrajKod                         object
Okres                           object
OkresKod                        object
SpravniObvod                    object
PoskytovatelTelefon             object
PoskytovatelFax                 object
DatumZahajeniCinnosti           object
IdentifikatorDatoveSchranky     object
PoskytovatelEmail               object
PoskytovatelWeb                 object
DruhPoskytovatele               object
PoskytovatelNazev               object
Ico                      

In [6]:
df_facilities.duplicated().sum()

1020

In [7]:
df_facilities = df_facilities.drop_duplicates()
print("Počet riadkov (dátová sada prevádzok):", len(df_facilities.index))

Počet riadkov (dátová sada prevádzok): 60962


#### Zistíme počty nedefinovaných hodnôt v jednotlivých stĺpcoch

In [8]:
df_facilities.isna().sum()

ZdravotnickeZarizeniId             0
PCZ                                0
PCDP                               0
NazevCely                          0
ZdravotnickeZarizeniKod            0
DruhZarizeniKod                    0
DruhZarizeni                       0
DruhZarizeniSekundarni         52297
Obec                               0
Psc                               50
Ulice                           3594
CisloDomovniOrientacni            69
Kraj                              22
KrajKod                            0
Okres                              1
OkresKod                           1
SpravniObvod                   52370
PoskytovatelTelefon            24274
PoskytovatelFax                53333
DatumZahajeniCinnosti              0
IdentifikatorDatoveSchranky    19513
PoskytovatelEmail              19325
PoskytovatelWeb                25457
DruhPoskytovatele                  3
PoskytovatelNazev                  0
Ico                                0
TypOsoby                           0
P

#### Preskúmame niektoré zaujímavé stĺpce dátovej sady, ktoré budú potrebné pre riešenie zadania

Zistíme, ktoré stĺpce rozlišujú jednotlivé záznamy

In [9]:
len(df_facilities.ZdravotnickeZarizeniId.unique())

39472

In [10]:
len(df_facilities.ZdravotnickeZarizeniKod.unique())

39472

In [11]:
len(df_facilities.NazevCely.unique())

30638

In [12]:
df_facilities.duplicated(subset=('ZdravotnickeZarizeniId','OborPece','FormaPece','DruhPece')).sum()

0

In [13]:
df_facilities.FormaPece.unique()

array(['ambulantní péče',
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - domácí péče - ošetřovatelská',
       'specializovaná ambulantní péče', 'primární ambulantní péče',
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - domácí péče - léčebně rehabilitační',
       nan,
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - umělá plicní ventilace',
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - návštěvní služba',
       'jednodenní péče', 'stacionární péče',
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - domácí péče - paliativní',
       'zdrav. péče poskytovaná ve vlastním soc. prostředí pacienta - dialýza',
       'následná lůžková léčebně rehabilitační péče',
       'následná lůžková péče - standardní',
       'akutní lůžková péče standardní', 'akutní lůžková péče intenzivní',
       'následná lůžková intenzivní péče',
       'dlouhodobá lůžková paliativní péče',
       'dlouhod

In [14]:
df_facilities.DruhPece.unique()

array([nan, 'ošetřovatelská péče', 'lékárenská péče',
       'léčebně rehabilitační péče', 'zdravotnická dopravní služba',
       'paliativní péče', 'lázeňská léčebně rehabilitační péče',
       'přeprava pacientů neodkladné péče',
       'zdravotnická záchranná služba',
       'protialkoholní a protitoxikomanická záchytná služba'],
      dtype=object)

Zistili sme, že jediné možné spojenie stĺpcov, ktoré navzájom odlišujú jednotlivé záznamy, je kombinácia stĺpcov 'ZdravotnickeZarizeniId', 'OborPece', 'FormaPece', 'DruhPece'. Pri vkladaní do databázy teda nebudeme používať ako identifikátor zariadenia stĺpec 'ZdravotnickeZarizeniId', ale budeme generovať vlastný, aby sme predišli konfliktom.

In [15]:
len(df_facilities.OborPece.unique())

158

In [16]:
df_facilities.OborPece.unique()

array(['všeobecné praktické lékařství', 'zubní lékařství', 'psychiatrie',
       'Všeobecná sestra', 'Zubní technik', 'Dentální hygienistka',
       'Fyzioterapeut', nan, 'anesteziologie a intenzivní medicína',
       'praktické lékárenství', 'rehabilitační a fyzikální medicína',
       'endokrinologie a diabetologie', 'oftalmologie',
       'dermatovenerologie', 'praktické lékařství pro děti a dorost',
       'vnitřní lékařství',
       'ortopedie a traumatologie pohybového ústrojí', 'Optometrista',
       'hematologie a transfúzní lékařství', 'Klinický logoped',
       'Klinický psycholog', 'gynekologie a porodnictví',
       'lékařská genetika', 'plastická chirurgie',
       'Sestra pro intenzivní péči', 'chirurgie',
       'tělovýchovné lékařství', 'urologie', 'kardiologie',
       'gastroenterologie',
       'Odborný pracovník v laboratorních  metodách a přípravě léčivých přípravků',
       'dětská neurologie', 'ortodoncie', 'Nutriční terapeut',
       'pneumologie a ftizeologie',

In [17]:
df_facilities.OborPece.value_counts()

všeobecné praktické lékařství                                                         6795
zubní lékařství                                                                       6120
Fyzioterapeut                                                                         3386
praktické lékařství pro děti a dorost                                                 2534
praktické lékárenství                                                                 2440
                                                                                      ... 
Behaviorální analytik                                                                    1
Odborný pracovník v ochraně a podpoře veřejného zdraví pro hygienu a epidemiologii       1
Bioanalytik pro mikrobiologii                                                            1
Bioanalytik pro klinickou genetiku                                                       1
nutriční podpora                                                                         1

In [18]:
len(df_facilities.DruhZarizeni.unique())

63

In [19]:
df_facilities.DruhZarizeni.unique()

array(['Samost. ordinace všeob. prakt. lékaře',
       'Samostatná ordinace PL - stomatologa',
       'Samostatná ordinace lékaře specialisty', 'Domácí zdravotní péče',
       'Samostatná stomatologická laboratoř',
       'Samostatné zařízení nelékaře - jiné',
       'Samostatné zařízení fyzioterapeuta',
       'Zdravotní péče v ústavech sociální p.', 'Lékárna',
       'Zdravotní ústav', 'Sam.ord.prakt.lékaře pro děti a dorost',
       'Oční optika', 'Samostatná odborná laboratoř',
       'Samostatné zařízení logopeda', 'Samostatné zařízení psychologa',
       'Samostatná ordinace PL - gynekologa',
       'Zdravotnická dopravní služba',
       'Výdejna zdravotnických prostředků', 'Lázeňská léčebna',
       'Lázeňský dům (jen ubyt. hotel. typu)',
       'Sdružené ambulantní zařízení - malé', 'Odběrová místnost',
       'Nemocnice následné péče', 'Zdravotnické středisko', 'Nemocnice',
       'Přeprava pacientů neodkladné péče',
       'Zařízení závodní preventivní péče', 'Hospic',
      

## Dátová sada Demografia

#### Načítame dátovú sadu demografického vývoja do pandas dataframe so správnym kódovaním a zobrazíme prvých 10 záznamov

In [20]:
df_demography = pd.read_csv('Dataset/130142-21data043021.csv', encoding='utf-8', delimiter=',', header=0)
df_demography.head(10)

idhod  hodnota  stapro_kod  pohlavi_cis  pohlavi_kod  vek_cis  vek_kod  \
0  738925968    55776        2406        102.0          1.0      NaN      NaN   
1  738935261   649245        2406        102.0          1.0      NaN      NaN   
2  738947654    79102        2406        102.0          1.0      NaN      NaN   
3  738960094    31506        2406        102.0          1.0      NaN      NaN   
4  738960494    42862        2406        102.0          1.0      NaN      NaN   
5  738960589    64075        2406        102.0          1.0      NaN      NaN   
6  738970385   610376        2406        102.0          1.0      NaN      NaN   
7  738970826   286361        2406        102.0          1.0      NaN      NaN   
8  738971828    23855        2406        102.0          1.0      NaN      NaN   
9  738948949    50682        2406        102.0          1.0      NaN      NaN   

   vuzemi_cis  vuzemi_kod   casref_do pohlavi_txt vek_txt          vuzemi_txt  
0         101       40665  2014-12-31         muž     NaN             Jihlava  
1         100        3026  2014-12-31         muž     NaN    Středočeský kraj  
2         101       40185  2014-12-31         muž     NaN              Kladno  
3         101       40380  2014-12-31         muž     NaN           Plzeň-jih  
4         101       40487  2014-12-31         muž     NaN               Louny  
5         101       40509  2014-12-31         muž     NaN             Teplice  
6         100        3018  2014-12-31         muž     NaN  Hlavní město Praha  
7         100        3131  2014-12-31         muž     NaN        Zlínský kraj  
8         101       40401  2014-12-31         muž     NaN            Rokycany  
9         101       40525  2014-12-31         muž     NaN          Česká Lípa

In [21]:
df_demography.tail(10)

idhod  hodnota  stapro_kod  pohlavi_cis  pohlavi_kod  vek_cis  \
63053  879154323     3762        2406        102.0          1.0   7700.0   
63054  879154324     5013        2406        102.0          1.0   7700.0   
63055  879154325     2176        2406        102.0          1.0   7700.0   
63056  879154326     5716        2406        102.0          1.0   7700.0   
63057  879154327     5902        2406        102.0          1.0   7700.0   
63058  879154328     4150        2406        102.0          1.0   7700.0   
63059  879154329     4700        2406        102.0          1.0   7700.0   
63060  879154330     8294        2406        102.0          1.0   7700.0   
63061  879154282     2653        2406        102.0          1.0   7700.0   
63062  879154281     2164        2406        102.0          1.0   7700.0   

            vek_kod  vuzemi_cis  vuzemi_kod   casref_do pohlavi_txt  \
63053  4.000006e+14         101       40843  2020-12-31         muž   
63054  4.000006e+14         101       40851  2020-12-31         muž   
63055  4.000006e+14         101       40860  2020-12-31         muž   
63056  4.000006e+14         101       40878  2020-12-31         muž   
63057  4.000006e+14         101       40886  2020-12-31         muž   
63058  4.000006e+14         101       40894  2020-12-31         muž   
63059  4.000006e+14         101       40908  2020-12-31         muž   
63060  4.000006e+14         101       40916  2020-12-31         muž   
63061  4.000006e+14         101       40436  2020-12-31         muž   
63062  4.000006e+14         101       40428  2020-12-31         muž   

                                       vek_txt     vuzemi_txt  
63053  0 až 5 (více nebo rovno 0 a méně než 5)         Vsetín  
63054  0 až 5 (více nebo rovno 0 a méně než 5)           Zlín  
63055  0 až 5 (více nebo rovno 0 a méně než 5)        Bruntál  
63056  0 až 5 (více nebo rovno 0 a méně než 5)  Frýdek-Místek  
63057  0 až 5 (více nebo rovno 0 a méně než 5)        Karviná  
63058  0 až 5 (více nebo rovno 0 a méně než 5)     Nový Jičín  
63059  0 až 5 (více nebo rovno 0 a méně než 5)          Opava  
63060  0 až 5 (více nebo rovno 0 a méně než 5)  Ostrava-město  
63061  0 až 5 (více nebo rovno 0 a méně než 5)   Karlovy Vary  
63062  0 až 5 (více nebo rovno 0 a méně než 5)           Cheb

In [22]:
df_demography.duplicated().sum()

0

In [23]:
print("Počet riadkov (dátová sada demografického vývoja):", len(df_demography.index))

Počet riadkov (dátová sada demografického vývoja): 63063


In [24]:
df_demography.dtypes

idhod            int64
hodnota          int64
stapro_kod       int64
pohlavi_cis    float64
pohlavi_kod    float64
vek_cis        float64
vek_kod        float64
vuzemi_cis       int64
vuzemi_kod       int64
casref_do       object
pohlavi_txt     object
vek_txt         object
vuzemi_txt      object
dtype: object

#### Zistíme počty nedefinovaných hodnôt v jednotlivých stĺpcoch

In [25]:
df_demography.isna().sum()

idhod              0
hodnota            0
stapro_kod         0
pohlavi_cis    21021
pohlavi_kod    21021
vek_cis         3003
vek_kod         3003
vuzemi_cis         0
vuzemi_kod         0
casref_do          0
pohlavi_txt    21021
vek_txt         3003
vuzemi_txt         0
dtype: int64

#### Preskúmame niektoré zaujímavé stĺpce dátovej sady ktoré budú potrebné pre riešenie zadania

In [26]:
df_demography.pohlavi_cis.unique()

array([102.,  nan])

In [27]:
df_demography.pohlavi_kod.unique()

array([ 1.,  2., nan])

In [28]:
df_demography.vek_cis.unique()

array([  nan, 7700.])

In [29]:
df_demography.vek_kod.unique()

array([          nan, 4.1002561e+14, 4.1005561e+14, 4.1001561e+14,
       4.1003561e+14, 4.1005061e+14, 4.1003061e+14, 4.1004061e+14,
       4.1006061e+14, 4.1002061e+14, 4.1004561e+14, 4.1007561e+14,
       4.1006561e+14, 4.1001061e+14, 4.1009061e+14, 4.0000561e+14,
       4.1008561e+14, 4.1009580e+14, 4.1007061e+14, 4.1008061e+14,
       4.0000060e+14])

In [30]:
df_demography.vek_txt.unique()

array([nan, '25 až 30 (více nebo rovno 25 a méně než 30)',
       '55 až 60 (více nebo rovno 55 a méně než 60)',
       '15 až 20 (více nebo rovno 15 a méně než 20)',
       '35 až 40 (více nebo rovno 35 a méně než 40)',
       '50 až 55 (více nebo rovno 50 a méně než 55)',
       '30 až 35 (více nebo rovno 30 a méně než 35)',
       '40 až 45 (více nebo rovno 40 a méně než 45)',
       '60 až 65 (více nebo rovno 60 a méně než 65)',
       '20 až 25 (více nebo rovno 20 a méně než 25)',
       '45 až 50 (více nebo rovno 45 a méně než 50)',
       '75 až 80 (více nebo rovno 75 a méně než 80)',
       '65 až 70 (více nebo rovno 65 a méně než 70)',
       '10 až 15 (více nebo rovno 10 a méně než 15)',
       '90 až 95 (více nebo rovno 90 a méně než 95)',
       '5 až 10 (více nebo rovno 5 a méně než 10)',
       '85 až 90 (více nebo rovno 85 a méně než 90)',
       'Od 95 (více nebo rovno 95)',
       '70 až 75 (více nebo rovno 70 a méně než 75)',
       '80 až 85 (více nebo rovno 80 a mén

## Identifikovanie stĺpcov, na základe ktorých je možné dátové sady prepojiť

Je zrejmé, že dátové sady bude možné prepájať iba pomocou geografickej informácie, a to buď pomocou kódu kraja, či okresu, alebo prostredníctvom textových názvov okresov a krajov

In [31]:
len(df_facilities.KrajKod.unique())

14

In [32]:
len(df_facilities.OkresKod.unique())

78

In [33]:
len(df_demography.vuzemi_kod.unique())

91

In [34]:
df_facilities.KrajKod.unique()

array(['CZ071', 'CZ080', 'CZ042', 'CZ041', 'CZ020', 'CZ052', 'CZ010',
       'CZ064', 'CZ051', 'CZ032', 'CZ072', 'CZ053', 'CZ031', 'CZ063'],
      dtype=object)

In [35]:
df_facilities.OkresKod.unique()

array(['CZ0712', 'CZ0714', 'CZ0715', 'CZ0804', 'CZ0802', 'CZ0425',
       'CZ0421', 'CZ0424', 'CZ0412', 'CZ0202', 'CZ0525', 'CZ0209',
       'CZ0100', 'CZ0805', 'CZ0642', 'CZ0643', 'CZ0647', 'CZ0522',
       'CZ0801', 'CZ0513', 'CZ020A', 'CZ0806', 'CZ0323', 'CZ0722',
       'CZ0533', 'CZ0316', 'CZ0204', 'CZ0208', 'CZ0532', 'CZ0724',
       'CZ0203', 'CZ0311', 'CZ0635', 'CZ0632', 'CZ020C', 'CZ0631',
       'CZ0314', 'CZ0633', 'CZ0534', 'CZ0326', 'CZ0711', 'CZ0426',
       'CZ0524', 'CZ0523', 'CZ0713', 'CZ020B', 'CZ0423', 'CZ0325',
       'CZ0427', 'CZ0521', 'CZ0205', 'CZ0511', 'CZ0634', 'CZ0411',
       'CZ0644', 'CZ0313', 'CZ0803', 'CZ0322', 'CZ0315', 'CZ0723',
       'CZ0206', 'CZ0422', 'CZ0327', 'CZ0312', 'CZ0317', 'CZ0413',
       'CZ0514', 'CZ0324', 'CZ0645', 'CZ0721', 'CZ0646', 'CZ0201',
       'CZ0207', 'CZ0531', 'CZ0512', 'CZ0641', 'CZ0321', nan],
      dtype=object)

In [36]:
df_demography.vuzemi_kod.unique()

array([40665,  3026, 40185, 40380, 40487, 40509,  3018,  3131, 40401,
       40525, 40223, 40461, 40274, 40576, 40452, 40894, 40878, 40258,
       40495, 40541, 40801, 40363, 40606,  3123, 40835, 40215, 40843,
       40819, 40908, 40614, 40720, 40771,  3093, 40789, 40827, 40428,
       40533, 40860, 40851, 40568, 40657, 40711, 40703, 40177, 40398,
       40436, 40517, 40207,  3051, 40231, 40371, 40673, 40649, 40304,
       40193, 40690,  3077,  3085, 40754, 40584, 40762, 40321, 40916,
       40169, 40339, 40282,  3140, 40240, 40631, 40886, 40410, 40681,
       40479, 40746, 40592,    19,  3107, 40738, 40291,  3069,  3115,
       40444, 40266, 40797, 40550, 40312, 40347,  3034,  3042, 40355,
       40622], dtype=int64)

Kódy pre kraje a okresy sa v dátových sadách nezhodujú. Overíme teda textové názvy.

In [37]:
len(df_facilities.Okres.unique())

78

In [38]:
len(df_facilities.Kraj.unique())

15

In [39]:
len(df_demography.vuzemi_txt.unique())

91

In [40]:
df_facilities[df_facilities.Okres.isna()]  

ZdravotnickeZarizeniId  PCZ  PCDP              NazevCely  \
48059                   40447    0     0  MUDr. Ivana Veselková   

       ZdravotnickeZarizeniKod  DruhZarizeniKod  \
48059           63109298000000              321   

                                 DruhZarizeni DruhZarizeniSekundarni   Obec  \
48059  Sam.ord.prakt.lékaře pro děti a dorost                    NaN  Praha   

           Psc  ... PscSidlo ObecSidlo UliceSidlo CisloDomovniOrientacniSidlo  \
48059  12800.0  ...      NaN       NaN        NaN                         NaN   

                                    OborPece        FormaPece DruhPece  \
48059  praktické lékařství pro děti a dorost  ambulantní péče      NaN   

      OdbornyZastupce  GPS         LastModified  
48059             NaN  NaN  2021-10-01 23:02:32  

[1 rows x 42 columns]

In [41]:
df_facilities.Okres.unique()

array(['Olomouc', 'Přerov', 'Šumperk', 'Nový Jičín', 'Frýdek-Místek',
       'Most', 'Děčín', 'Louny', 'Karlovy Vary', 'Beroun', 'Trutnov',
       'Praha-východ', 'Hlavní město Praha', 'Opava', 'Brno-město',
       'Brno-venkov', 'Znojmo', 'Jičín', 'Bruntál', 'Liberec',
       'Praha-západ', 'Ostrava-město', 'Plzeň-město', 'Uherské Hradiště',
       'Svitavy', 'Strakonice', 'Kolín', 'Nymburk', 'Pardubice', 'Zlín',
       'Kladno', 'České Budějovice', 'Žďár nad Sázavou', 'Jihlava',
       'Rakovník', 'Havlíčkův Brod', 'Písek', 'Pelhřimov',
       'Ústí nad Orlicí', 'Rokycany', 'Jeseník', 'Teplice',
       'Rychnov nad Kněžnou', 'Náchod', 'Prostějov', 'Příbram',
       'Litoměřice', 'Plzeň-sever', 'Ústí nad Labem', 'Hradec Králové',
       'Kutná Hora', 'Česká Lípa', 'Třebíč', 'Cheb', 'Břeclav',
       'Jindřichův Hradec', 'Karviná', 'Klatovy', 'Prachatice', 'Vsetín',
       'Mělník', 'Chomutov', 'Tachov', 'Český Krumlov', 'Tábor',
       'Sokolov', 'Semily', 'Plzeň-jih', 'Hodonín', 'Kro

In [42]:
df_facilities.Kraj.unique()

array(['Olomoucký kraj', 'Moravskoslezský kraj', 'Ústecký kraj',
       'Karlovarský kraj', 'Středočeský kraj', 'Královéhradecký kraj',
       'Hlavní město Praha', 'Jihomoravský kraj', 'Liberecký kraj',
       'Plzeňský kraj', 'Zlínský kraj', 'Pardubický kraj',
       'Jihočeský kraj', 'Kraj Vysočina', nan], dtype=object)

In [43]:
df_demography.vuzemi_txt.unique()

array(['Jihlava', 'Středočeský kraj', 'Kladno', 'Plzeň-jih', 'Louny',
       'Teplice', 'Hlavní město Praha', 'Zlínský kraj', 'Rokycany',
       'Česká Lípa', 'Mladá Boleslav', 'Chomutov', 'Rakovník', 'Jičín',
       'Děčín', 'Nový Jičín', 'Frýdek-Místek', 'Praha-západ', 'Most',
       'Liberec', 'Přerov', 'Klatovy', 'Trutnov', 'Olomoucký kraj',
       'Uherské Hradiště', 'Mělník', 'Vsetín', 'Šumperk', 'Opava',
       'Chrudim', 'Brno-venkov', 'Jeseník', 'Pardubický kraj', 'Olomouc',
       'Kroměříž', 'Cheb', 'Jablonec nad Nisou', 'Bruntál', 'Zlín',
       'Hradec Králové', 'Havlíčkův Brod', 'Brno-město', 'Blansko',
       'Beroun', 'Plzeň-sever', 'Karlovy Vary', 'Ústí nad Labem',
       'Kutná Hora', 'Karlovarský kraj', 'Nymburk', 'Plzeň-město',
       'Pelhřimov', 'Ústí nad Orlicí', 'Jindřichův Hradec', 'Kolín',
       'Žďár nad Sázavou', 'Liberecký kraj', 'Královéhradecký kraj',
       'Vyškov', 'Náchod', 'Znojmo', 'Prachatice', 'Ostrava-město',
       'Benešov', 'Strakonice', 'Čes

In [44]:
regions_df1 = df_facilities.Okres.unique().tolist()
regions_df2 = df_demography.vuzemi_txt.unique().tolist()
total = 0

for i in range(len(regions_df1)):
    if regions_df1[i] in regions_df2:
        total += 1
    else:
        print("Nezhodný región:", regions_df1[i])

if total == len(regions_df1):
    print("Názvy okresov sa zhodujú, je teda možné datasety spájať na základe názvu okresu")

Nezhodný región: nan
